networks:
  default:
    external:
      name: proxy

services:
  redis:
    image: redis
    restart: unless-stopped

  pictoid:
    image: node:18
    container_name: pictoid
    depends_on:
      - redis
    restart: unless-stopped
    command: yarn --cwd /app prod
    volumes:
      - .:/app/
    labels:
      - traefik.enable=true
      - traefik.http.routers.pictoid.entrypoints=websecure
    expose:
      - 8080