networks:
  default:
    external:
      name: proxy

services:
  redis:
    image: redis
    restart: unless-stopped

  pictoid:
    build: .
    container_name: pictoid
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - .:/app/
    labels:
      - traefik.enable=true
      - traefik.http.routers.pictoid.entrypoints=websecure
    expose:
      - 8080
