version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"